<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Zend\Form\Fieldset $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$assetUrl = $plugins->get('assetUrl');

$this->htmlElement('body')->appendAttribute('class', 'sites site-settings');

$this->headLink()->appendStylesheet($assetUrl('css/blocks-disposition.css', 'BlocksDisposition'));
$this->headScript()->appendFile($assetUrl('js/blocks-disposition.js', 'BlocksDisposition'));

$form->prepare();
?>

<?= $this->pageTitle($site->title(), 1, $translate('Sites')) ?>
<?= $this->form()->openTag($form) ?>
<div id="page-actions">
    <?= $this->cancelButton() ?>
    <button><?= $translate('Save') ?></button>
</div>
<?= $this->formCollection($form) ?>
<?= $this->form()->closeTag() ?>
